### ISSUE TITLE
bash

### ISSUE THREAD

**Issue by freeformflow** [pandastrike/fairmont#21]
I'm not sure how much of a faux pas it is to use third party libraries here, but it would be nice to have a handy function for executing arbitrary bash commands.  ShellJS's "exec" can run asynchronously and I find myself writing this function repeatedly, haha.  I should be better about writing more refined error handling, though.  @dyoder, could you consider adding this function to the File System Functions, please?

``` coffee
{exec} = require "shelljs"
{promise} = require "when"

bash = (command) ->
  promise (resolve, reject) ->
    exec command, (code, output) ->
      if code == 0
        resolve output
      else
        reject output
```

> One thing to note is that ShellJS has [admitted to inefficiencies for long lived processes](https://github.com/arturadib/shelljs#execcommand--options--callback).  They promise to address this in the future.

**Comment by dyoder** [comment]
We could probably do this with the native Node APIs, replacing ShellJS entirely. I'm not ShellJS is that useful now that we have generator functions. Let me play around a bit.
