### ISSUE TITLE
Ignoring Rejected Promises

### ISSUE THREAD

**Issue by freeformflow** [pandastrike/fairmont#22]
Hey @dyoder, I have another proposal.  Sometimes we don't care if a promise is rejected, we just need to wait for it to be done one way or another.  I propose a function that accepts an input promise, p, but always resolves "true".

I had a specific and legitimate use-case when I wrote the original version, but I was unsure about abstracting it to submit this to you for Fairmont.  
1.  On one hand, it can be handy to have a function that grants a kind of idempotence to an arbitrary function, but
2. This is a dangerous function because you end up losing state and errors could be hard to catch.  

I try to be mindful of Crockford's advice to avoid dangerous styles, so please know I don't submit this lightly.  I'd understand if you have misgivings and I'd really like your opinion.  

**source**

``` coffee
force = (p, args...) ->
  {partial} = require "./core"
  {promise} = require "when"

  # Compose the promise that was passed in.
  p = partial p, args...

  # Evaluate the promise to achieve its side effects, but always resolve true.
  promise (resolve, reject) ->
    p.catch resolve true
    call -> yield p()
    resolve true
```

**example**

``` coffee
# The affected function is passed into "force", with its arguments following it instead of being passed directly. 
call ->
  # This one fails out if the alias is not present.
  yield shell "git remote rm  #{argv[0]}"

  # This one will quietly continue to the next line.
  yield force shell, "git remote rm  #{argv[0]}"
```

**Comment by freeformflow** [comment]
Okay, based on our conversation, this would be better implemented as a try-catch block.

``` coffee
async = (require "when/generator").lift
force = async (f, args...) ->
  try
    yield f args...
  catch e
    void
```

**Comment by freeformflow** [comment]
So, apparently `void` is a reserved word in CoffeeScript.  I'd suggest using `null`.  It's probably the value that would cause the least amount of harm and would give the external functions a way to know if a rejected promise had to be ignored.

``` coffee
async = (require "when/generator").lift
force = async (f, args...) ->
  try
    yield f args...
  catch e
    null
```

**Comment by dyoder** [comment]
My point there was that wrapping things in a `try/catch` block is such a common idiom that there is no need for a `force` function. In fact, it's suspect to silently ignore errors, so that would fall under Crockford's warning.

The thing that is nice about throwing is that you don't have to handle the error at the site where it occurred. The error will propagate back up through the call stack until it reaches a `try/catch` block.

At any rate, I don't think this function is a good idea.
