### ISSUE TITLE
`clone` fails with "ReferenceError: $ is not defined"

### ISSUE THREAD

**Issue by PandaWhisperer** [pandastrike/fairmont#26]
Example:

``` coffeescript
{clone} = require "fairmont"
clone foo: "bar"
```

Result

```
fairmont/lib/object.js:67
        clone[key] = $.clone(object[key]);
                     ^
ReferenceError: $ is not defined
  at clone (fairmont/lib/object.js:67:22)
  at repl:1:5
```

It appears that the `clone` method is referencing `$.clone`, which does not exist. 

Also there are no tests for `clone`.

**Comment by PandaWhisperer** [comment]
I tried looking into this, but the link referenced in the the description of the clone method does not load for me.

http://coffeescriptcookbook.com/chapters/classes_and_objects/cloning

**Comment by dyoder** [comment]
I'm not sure what code you're using. This is the current code:

https://github.com/pandastrike/fairmont/blob/master/src/object.litcoffee#clone

There's no reference to `$`.

**Comment by dyoder** [comment]
The CoffeeScript cookbook appears to be down…

**Comment by PandaWhisperer** [comment]
I followed that link, and it still references `$.clone`.
