### ISSUE TITLE
`pick` and `omit` à la underscore.js

### ISSUE THREAD

**Issue by PandaWhisperer** [pandastrike/fairmont#29]
I'd like something like underscore's [`pick`](http://underscorejs.org/#pick) and [`omit`](http://underscorejs.org/#omit) in fairmont.

**Comment by dyoder** [comment]
Closed in Alpha 14.

**Comment by dyoder** [comment]
By the way, this doesn't work quite the same as Underscore. It's more fuctionally-oriented. But you can filter by property name by using a partial application for `includes`:

``` coffee
pick (partial includes, _, (w "foo bar baz")), object
```

We could do something like `pick_by` that takes a function and `pick` just takes a list of properties.
