### ISSUE TITLE
where() and array_equal()

### ISSUE THREAD

**Issue by freeformflow** [pandastrike/fairmont#40]
@dyoder, there is a function in `underscore` that I think is very handy, called `where()`.  Provided an array of objects and a query object, `where()` returns an array with only those objects that contain the query object as a subset.

I liked it so much that when we switched the Huxley CLI over to Fairmont, [I re-implemented it](https://github.com/pandastrike/huxley/blob/development/alpha-02/huxley-cli/src/helpers.coffee#L85-L99).  However, I went back and thought about the style I've been trying to practice.  I think the version below is much closer to something that could be included in Fairmont, so I'd like to submit it to you.  

There are a couple questions of scope, however.  It currently only works on an array of objects and accepts only one query object.
- Should we generalize it to accept an array of strings, numbers, etc....
- Should we generalize it to accept multiple queries for matching?

I toyed with the idea of making an awesome, overloaded filter function but there are so many edge cases it was like wrangling cats, haha.  
### Object Filter Draft, where()

``` coffee
# Filters an array of objects against a single "query" object.  If no objects match, an empty array is returned.
{async, collect, deep_equal, partial, select, _} = require "fairmont"
where = async (query, array) ->
  match = (a, b) ->
    intersect = (a, b) -> key for key in Object.keys(b) when (deep_equal a[key], b[key])
    if intersect(a, b).length == Object.keys(a).length then true else false

    collect yield select (partial match, query, _), array
```

During testing, I realized that not only does the `==` operator fail to compare arrays, so does `deep_equal`.  I wrote a draft of a function that performs a comparison on arrays and recurses to ensure a deep comparison.  Since this could possibly be expensive, it tries to escape and return `false` whenever it confirms a difference.  Maybe we can work this into `deep_equal` eventually. (after removing the `deep_equal` usage, haha.)
### Deep Array Comparison Draft, array_equal()

``` coffee
# Performs deep comparison of two arrays.  Returns true or false.
{type, deep_equal} = require "fairmont"
array_equal = (a, b) ->
  throw "\"array_equal\" accepts only arrays." unless type(a) == "array" && type(b) == "array"
  return false unless a.length == b.length

  compare = (a, b) ->
    for i in [0..a.length - 1]
      if (type(a[i]) == "array") && (type(b[i]) == "array")
        throw false unless  (a.length == b.length) && (compare a[i], b[i])
      else
        throw false unless deep_equal a[i], b[i]
    true

  try
    compare a, b
  catch e
    false
```

``` coffee
assert array_equal [[1, 2, 3], 2, 3], [[1, 2, 3], 2, 3]
assert !array_equal [[1, 2, 30], 2, 3], [[1, 2, 3], 2, 3]
assert array_equal [[[{one: {two:2, three:3}}, 2, 3], 2, 3], 2, 3], [[[{one: {two:2, three:3}}, 2, 3], 2, 3], 2, 3]
```

**Comment by dyoder** [comment]
A few points of feedback.
- `where` should be an iterator function, not an array function.
- Can you give me a test case where `deep_equal` fails on arrays? That's a bug.
- I think the way to implement this is to implement a `query` function. That might be the wrong name for it. But this should basically be:

``` coffee
where = select query
```

where all the real work is in `query`
- `query` itself should be simple. Something like this.

``` coffee
query = curry (example, target) ->
  if is_object example && is_object target
    for k, v of example when query v, target[k]
  else 
    deep_equal example, target
```

**Comment by dyoder** [comment]
I've added `query` and `where` support to alpha 17. Still not sure what the failing case is for `deep_equal` on arrays. But I'm closing this for now. Please open a new ticket with the failing test case for arrays.

**Comment by freeformflow** [comment]
@dyoder, thank you.  When I went back, I wasn't able to reproduce the issue with arrays, so I must have been mistaken before.

btw, in your test with `query`, the name of the princess in _Sleeping Beauty_ is Aurora, haha.
