### ISSUE TITLE
NPM Module Version Check

### ISSUE THREAD

**Issue by freeformflow** [pandastrike/fairmont#51]
@dyoder, when I run `npm install fairmont` in a test directory, I do not get the latest version of Fairmont.  I get one that appears to have been released around the beginning of 2015.  Is this intentional? 

``` shell
David:test David$ npm install fairmont
npm WARN package.json test@1.0.0 No description
npm WARN package.json test@1.0.0 No repository field.
npm WARN package.json test@1.0.0 No README data
fairmont@0.8.2 node_modules/fairmont
```

``` shell
David:test David$ npm install fairmont@1.0.0-beta-30
npm WARN package.json test@1.0.0 No description
npm WARN package.json test@1.0.0 No repository field.
npm WARN package.json test@1.0.0 No README data
fairmont@1.0.0-beta-30 node_modules/fairmont
├── fairmont-crypto@1.0.0-beta-19
├── fairmont-multimethods@1.0.0-beta-19
├── fairmont-core@1.0.0-beta-21
├── fairmont-reactive@1.0.0-beta-32 (when@3.7.3)
├── fairmont-process@1.0.0-beta-19 (when@3.7.3)
├── fairmont-helpers@1.0.0-beta-22 (when@3.7.3, coffee-script@1.9.3)
└── fairmont-filesystem@1.0.0-beta-20 (when@3.7.3, minimatch@2.0.10)
```

**Comment by dyoder** [comment]
Yeah, unfortunately it appears NPM has adopted a policy of requiring the version tag when dealing with releases that have a modifier, such as `beta`. I haven't bothered to figure out exactly how this works. But it isn't intentional. I was surprised as well. And now that I think about it, I guess the READMEs are all wrong.

**Comment by cardoni** [comment]
This seems like a stale ticket that has since resolved itself.
![image](https://cloud.githubusercontent.com/assets/674107/14042907/8451bf6e-f23b-11e5-92e1-275cda8cedf7.png)
Please let me know if this is not the case.

**Comment by dyoder** [comment]
Not sure, but in any event, we did a 1.0 release, so…
